# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Prettier Java Action
      # You may pin to the exact commit or the version.
      # uses: lukasmwerner/prettier_action_java@ed1b1c8ee98efb25adda9f54e1a28c19d246b70c
      uses: lukasmwerner/prettier_action_java@v1.1.1
    - name: Build with Maven
      run: mvn -B package --file java-servlet-project/pom.xml
    - name: Caching dependencies
      run: mvn --batch-mode --update-snapshots verify --file java-servlet-project/pom.xml
    - run: mkdir staging && cp java-servlet-project/target/*.war staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Maven Dependency Tree Dependency Submission
      uses: advanced-security/maven-dependency-submission-action@v2.0.1
      with:
        directory: java-servlet-project/

